apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-tls
  namespace: nats
spec:
  secretName: nats-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - nats.ltw8.net
