---
apiVersion: v1
kind: Namespace
metadata:
  name: k8up-system
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
