deployment:
  replicas: 1

ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

ports:
  web:
    port: 8000
    exposedPort: 80
    protocol: TCP
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    port: 8443
    exposedPort: 443
    protocol: TCP
  mqtt:
    port: 1883
    exposedPort: 1883
    protocol: TCP
    expose:
      default: true
  nats:
    port: 4222
    exposedPort: 4222
    protocol: TCP
    expose:
      default: true

service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.8.10.200"

logs:
  general:
    level: INFO
  access:
    enabled: true

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  capabilities:
    drop:
      - ALL

podSecurityContext:
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault
