apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthchecks
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthchecks
  template:
    metadata:
      labels:
        app: healthchecks
    spec:
      containers:
        - name: healthchecks
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                wget -q -O /dev/null https://hc-ping.com/69073593-7e23-4781-82df-4271e90b3be1
                sleep 300
              done
          resources:
            requests:
              cpu: 1m
              memory: 8Mi
            limits:
              cpu: 10m
              memory: 16Mi
      restartPolicy: Always
