---
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoriametrics-config
  namespace: observability
  labels:
    app: victoriametrics
data:
  scrape.yaml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: 'victoriametrics'
        static_configs:
          - targets: ['localhost:8428']

      # - job_name: 'kubernetes-pods'
      #   kubernetes_sd_configs:
      #     - role: pod
      #   relabel_configs:
      #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      #       action: keep
      #       regex: true
      #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      #       action: replace
      #       target_label: __metrics_path__
      #       regex: (.+)
      #     - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      #       action: replace
      #       regex: ([^:]+)(?::\d+)?;(\d+)
      #       replacement: $1:$2
      #       target_label: __address__
      #     - source_labels: [__meta_kubernetes_pod_name]
      #       action: replace
      #       target_label: pod
      #     - source_labels: [__meta_kubernetes_namespace]
      #       action: replace
      #       target_label: namespace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoriametrics-data
  namespace: observability
  labels:
    app: victoriametrics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriametrics
  namespace: observability
  labels:
    app: victoriametrics
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8428"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: victoriametrics
          image: victoriametrics/victoria-metrics:v1.104.0
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          args:
            - -storageDataPath=/data
            - -retentionPeriod=99y
            - -promscrape.config=/config/scrape.yaml
            - -memory.allowedPercent=60
            - -search.maxUniqueTimeseries=50000
            - -search.maxStalenessInterval=5m
            - -httpListenAddr=:8428
          ports:
            - name: http
              containerPort: 8428
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "384Mi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: victoriametrics-data
        - name: config
          configMap:
            name: victoriametrics-config
---
apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: observability
  labels:
    app: victoriametrics
spec:
  type: NodePort
  selector:
    app: victoriametrics
  ports:
    - name: http
      port: 8428
      targetPort: http
      nodePort: 30428
      protocol: TCP
