# unifi-credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: unifi-credentials
  namespace: unifi-cert
type: Opaque
stringData:
  username: "cert-deployer"
  password: "DEIN_UNIFI_PASSWORT"
  host: "10.8.10.1"
